--- #example of unarchieving zip files
- hosts: localhost
  user: root
  connection: ssh
  become: yes
  gather_facts: yes
  tasks:
  - name: unarchiveing webserver.yml.zip
    environment:
    unarchive: src=/root/roles/webserver.yml.zip dest=/root/playbooks

