--- #example of user module

- hosts: all
  user: root
  connection: ssh
  become: yes
  gather_facts: yes
  tasks:
  - name: add the user called tstapache to the apache web client
    user: name=tst comment="tst user" shell=/bin/bash groups=wheel append=yes
